[package]
name = "rust-bms"
version = "0.1.0"
authors = ["yuf"]

[[bin]]
name = "rust-bms"

[dependencies]
piston = "0.32.0"
piston2d-graphics = "0.21.1"
pistoncore-glutin_window = "0.37.0"
piston2d-opengl_graphics = "0.44.0"
ears = "0.4.0"
rand = "*"
